[cmake]
version = "3.15"

[project]
name = "MCPx64dbg"
description = "x64dbg Plugin Module"
msvc-runtime = "dynamic"

[variables]
pluginsdk_dir = "${source_dir}/pluginsdk"

[conditions]
x86 = "CMAKE_SIZEOF_VOID_P EQUAL 4"
x64 = "CMAKE_SIZEOF_VOID_P EQUAL 8"

[target.${project.name}]
type = "shared"
sources = ["*.cpp"]
suffix = "$if($eq($sizeof(void*),4),.dp32,.dp64)"
include-directories = [
    "${source_dir}",
    "${pluginsdk_dir}"
]

# 架构特定的库配置
x86.private-link-libraries = [
    "ws2_32",
    "winhttp",
    "${pluginsdk_dir}/TitanEngine/TitanEngine_x86.lib",
    "${pluginsdk_dir}/DeviceNameResolver/DeviceNameResolver_x86.lib",
    "${pluginsdk_dir}/jansson/jansson_x86.lib",
    "${pluginsdk_dir}/lz4/lz4_x86.lib",
    "${pluginsdk_dir}/XEDParse/XEDParse_x86.lib",
    "${pluginsdk_dir}/x32dbg.lib",
    "${pluginsdk_dir}/x32bridge.lib"
]

x64.private-link-libraries = [
    "ws2_32",
    "winhttp",
    "${pluginsdk_dir}/TitanEngine/TitanEngine_x64.lib",
    "${pluginsdk_dir}/DeviceNameResolver/DeviceNameResolver_x64.lib",
    "${pluginsdk_dir}/jansson/jansson_x64.lib",
    "${pluginsdk_dir}/lz4/lz4_x64.lib",
    "${pluginsdk_dir}/XEDParse/XEDParse_x64.lib",
    "${pluginsdk_dir}/x64dbg.lib",
    "${pluginsdk_dir}/x64bridge.lib"
]

# 后构建消息
cmake-after = """
add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E echo \"\"
    COMMAND ${CMAKE_COMMAND} -E echo \"=== Plugin Build Complete ===\"
    COMMAND ${CMAKE_COMMAND} -E echo \"Output: $<TARGET_FILE:${PROJECT_NAME}>\"
    COMMAND ${CMAKE_COMMAND} -E echo \"Install: $ENV{ProgramFiles}/x64dbg/release/$<IF:$<EQUAL:${CMAKE_SIZEOF_VOID_P},4>,x32,x64>/plugins/$<TARGET_FILE_NAME:${PROJECT_NAME}>\"
    COMMAND ${CMAKE_COMMAND} -E echo \"============================\"\n
)
"""

[cxx]
standard = 17
required = true