name: CMake Multi-Arch Build

on: [ push, pull_request ]

jobs:
  build:
    name: Build Win32/x64
    runs-on: windows-latest  # 预装 VS2022 和 CMake

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # x64 架构构建
      - name: Build x64
        shell: cmd
        run: |
          rmdir /s /q cmake-build-debug
          cmake -G "Visual Studio 17 2022" -A x64 -S . -B cmake-build-debug
          cmake --build cmake-build-debug --config Release --parallel 6
          copy cmake-build-debug\Release\MCPx64dbg.dp64 .

      # Win32 架构构建
      - name: Build Win32
        shell: cmd
        run: |
          rmdir /s /q cmake-build-debug
          cmake -G "Visual Studio 17 2022" -A Win32 ^
            -T "host=x64" ^
            -S . -B cmake-build-debug
          cmake --build cmake-build-debug --config Release --parallel 6
          copy cmake-build-debug\Release\MCPx64dbg.dp32 .

      # 上传构建结果
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: multiarch-binaries
          path: |
            MCPx64dbg.dp64
            MCPx64dbg.dp32